---
title: "How Not to Manage the News"
author: "Anon"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
    toc: no
    keep_tex: yes
    fig_caption: no
    includes:
      in_header: 
        - kableextra-dependencies.tex
mainfont: Fira Sans
mainfontoptions: Scale=MatchLowercase
geometry: margin=1.4in
linestretch: 1.1
bibliography: ../rBib.bib
fontsize: 12pt
---

```{r, include=FALSE}
require(knitr)
require(tidyverse)
require(kableExtra)

knitr::opts_chunk$set(echo = FALSE, results = "asis")

gameformat <- function(game){
  labelgame <- rbind(
    c("", names(game)[2:length(names(game))]),
    game
  )
  labelgame %>%
    kbl(booktabs = T, 
        col.names = NULL, 
        escape = FALSE,
        align = paste0("r",strrep("c", ncol(game)-1)),
        linesep = "") %>%
    column_spec(1, border_right = T) %>%
    row_spec(1, hline_after = TRUE) %>%
    kable_styling(latex_options = "hold_position")
  # as_hux(game) %>%
  #   set_markdown_contents(1, 1, "") %>%
  #   set_right_border(everywhere, 1, value = 0.4) %>%
  #   set_bottom_border(1, everywhere, value = 0.4) %>%
  #   set_align(everywhere, everywhere, "center") %>%
  #   set_align(everywhere, 1, "right") %>%
  #   set_valign(1, everywhere, "middle") %>%
  #   set_all_padding(everywhere, everywhere, 2) %>%
  #   set_top_padding(1, everywhere, 0) %>%
  #   set_bottom_padding(1, everywhere, 6) %>%
  #   set_latex_float("h!")
}
```

J. Dmitri @Gallow2020 proposed an adjustment to causal decision theory to handle cases like Death in Damascus. The adjustment is ingenious, but it creates problems that are bigger than those it aimed to solve. 

Gallow's theory has two main parts, the first dealing with choice between two options, and the second extending the theory to choice between more than two options.

The part of the theory dealing with binary choice is easiest to understand in terms of regret.^[I'm simplifying a bit here; see section 2 of Gallow's paper for a more detailed presentation.] $A$ is preferable to $B$ iff the chooser regrets choosing $B$ when they could have chosen $A$ more than they regret choosing $A$ when they could have chosen $B$. More formally, let $I$ be an _improvement_ function, in the following sense. ('Improvement' here is basically the converse of regret.) $I_C(A, B)$ is the weighted average of $D(AK) - D(BK)$, where $K$ is a possible state of the world that's causally independent of the choice, $D$ measures the desirability of choice-state pairs, and the weights are given by $\Pr(K | C)$. That is, the weights are conditional probabilities of states given choices. Very very roughly, $I_C(A, B)$ measures how much better off you would have been choosing $A$ rather than $B$, assuming you did actually choose $C$. Gallow is primarily interested in the special case where $A = C$; only that special case will play a role in what follows. The news value $N$ of $A$ over $B$ is defined as $I_A(A, B) - I_B(B, A)$. In the case where there are only two options, $A$ is strictly preferred to $B$ iff $N(A, B) > 0$.