---
title: "Annual Report"
author: "Brian Weatherson"
format: docx
---

My most important research news this year is that my third book, _Knowledge: A Human Interest Story_, has gone through the review process at Open Book Publishers, and should be on its way to publication. I'm happy this is finally coming out, and that it will be with a leading open access publisher. The book draft is at <https://brian.weatherson.org/kahis>. I hope it will not just get philosophers talking about knowledge and interests, but start a broader conversation about how different debates within epistemology should be connected. For now we're moving onto final edits after the reviewers comments, and then the usual work of getting a book into final publication.

In Fall last year I taught a graduate seminar on the philosophical work of John Maynard Keynes. And one of the projects I've been working on since then came out of the seminar. There has been a resurgence of interest in philosophy in questions about the metaphysics of money, in part because of the general rise in interest in social metaphysics, and in part because of the interesting questions raised by crypto-currencies.

Keynes, as I read him, has a plausible theory about what it takes for something to be money: it's for it to be liquid, i.e., easy to trade for goods and services, and have low carrying costs. I've been working on (a) whether that's really what Keynes thinks, (b) whether it's a plausible theory, and (c) if it is plausible, what does it say about which other things are money. For instance, I think on this theory Walmart gift cards turn out to be money, which I think is probably a plausible view. One other feature of money is that prices are relatively stable, at least day-to-day, in the local money. Sure things go on sale, and prices go up, but most of the time most things cost the same number of US dollars today as they did yesterday. Maybe that's something that should count as definitional of money, and maybe Keynesian liquidity should include this kind of day-to-day price stability. (Just like Keynes's theory of the labor market assumes that most workers get paid the same number of dollars per hour one week as the last.) If so, that would rule out Bitcoin being money, since prices are really not stable in it. But this is all very much work in progress.

I did a talk on this a couple of times in Spring which went well, and the slides for it are at <http://brian.weatherson.org/money/>.

The main other things I've been working on have also been at the intersection of philosophy and economics. 

I used some work on signaling games to show that, contrary to what most decision theorists thought, there are situations where Evidential Decision Theory leaves proponents with less money than Causal Decision Theory. This paper, called "Why Ain't Evidentialists Rich?", is coming out in _Analysis_ and the final draft is online at <http://brian.weatherson.org/quarto/posts/war-on-war/war-on-war.html>.

I've also been working on what we should say about the applicability of decision theory to real people who can't perform the arbitrarily difficult calculations that decision theory asks them to do. I think this is a bigger problem than most decision theorists have appreciated. A lot of arguments in decision theory say that theory has to take such-and-such direction or else it won't be usable. But the theory people come up with requires isn't usable anyway - it requires that everyone have a supercomputer in their head! Still, I think there are reasons to do this kind of idealised theory. It can be useful not to people actually making decisions, but to social scientists who need an approximately correct theory to understand some aspects of human behavior. Of course, we need to be careful about just when it is even approximately correct, but I think in some special circumstances, when people face repeated choices and get lots of feedback on the results of choices they and people around them make, it is close enough to correct. I've presented this at a couple of workshops, and the slides are at <http://brian.weatherson.org/teodt/>.

The biggest thing I'm currently working on a much bigger project connecting work on game theory by economists to puzzles in decision theory. The current proposal involves working out the consequences of something I call the Single Choice Principle. The idea is that in any decision tree where there is only one node where Chooser can move, the rational choices at that node are exactly the same as the rational choices in the purely strategic form of the game. Pretty much every approach to game theory endorses this principle, and from a game-theoretic perspective it looks fairly weak. But just about every approach to decision theory in philosophy turns out to be inconsistent with it. I have a very long (i.e., 20,000 words) draft showing this, but this is much too long for regular journals. So I'm currently trying to edit/rewrite it to get it back to a reasonable length. But I think this should be a good paper when it's done.

Finally, I've had some surprising invitations in the last little while.

I've been invited to present at a conference in Tilburg, Netherlands on digital humanities, commenting on a recent book on citations and acknowledgments in philosophy journals. I was invited in part because of my book on topic modeling, and in part because apparently I'm thanked a lot in various acknowledgment sections over the years! I wrote up some comments on the suggestion (in the book I'm commenting on) that there was a big change in philosophy circa 2000. I'm a little sceptical of the claim, but I do think studying the citation patterns can tell us something interesting about the recent history of philosophy. The slides for my talk (which is in a few weeks) are at <https://brian.weatherson.org/tilburg/>.

And I was also invited to be a commentator in a book on Buddhist logic. I don't really know anything about Buddhist philosophy, but they wanted people who could relate the 8th-13th century Buddhist work to contemporary philosophy, which I guess is where I come in. So I'm writing up some comments on the Buddhist idea, which seems really interesting, that in most cases, when someone knows something, it is 'intrinsically determined' that they know it. The volume this is in will hopefully come out in 2025 or 2026.

