---
title: "Anti-Anti-Desire-As-Belief"
abstract: |
  David Lewis put forward a decision theoretic argument against there being a tight connection between desires and beliefs about the good. I argue that his argument fails twice over. It makes inconsistent background assumptions about his opponents' views, and it over-generates so broadly that if it worked, it would also rule out some standard economic models. I end with a puzzle that arises from the response to Lewis. If one responds to moral uncertainty by saying one should maximise expected moral value, how does one treat cases where one's action is evidence for or against the goodness of different actions?
date: November 2024
bibliography: /Users/weath/Documents/quarto-articles/brian-quarto.bib
number-sections: true
author:
  - name: Anon
format:
    html: default
    docx:
      reference-doc: my-template.docx
    pdf: 
      geometry: "left=1.5in,right=1.5in,top=1.78in,bottom=1.78in"
      mathfont: EB Garamond Math
      mainfont: EB Garamond Math
      sansfont: EB Garamond SemiBold
      mainfontoptions: 
        - ItalicFont=EB Garamond Italic
        - BoldFont=EB Garamond SemiBold
      fontsize: 12pt
      linkcolor: black
      urlcolor: black
      colorlinks: false
      linestretch: 1.75
      link-citations: true
      output-file: "Anti-Anti-Desire-As-Belief"
      include-in-header:
        text: |
          \setlength\heavyrulewidth{0ex}
          \setlength\lightrulewidth{0ex}
---

# The Cast

A particular kind of anti-Humean, call her Auntie, believes there is a tight connection between wanting something and believing that it is good. David Lewis [-@Lewis1988; -@Lewis1996] has a famous argument that Auntie's view is incoherent. The point of this note is to respond on Auntie's behalf. The response will be in an important respect not at all novel. What I'm going to do is essentially put together the responses offered by Huw @Price1989 and Jessica @Collins2015, and show that between them, they offer a response that any Auntie can accept, and so Lewis's argument shouldn't make any of them lose a moment's sleep.

I'm going to distinguish two kinds of Aunties, I'll call them Auntie C and Auntie E, and argue that both of them can satisfy the description _believes there is a tight connection between wanting something and believing that it is good_, and that they each have a principled reason to reject one of the premises in Lewis's anti-Auntie argument. I'll then argue that there is no one who should have accepted all the premises of Lewis's argument in the first place.

To do this, we need one last character. Auntie is of course an Auntie of someone; call the someone Peter. Naturally enough, Auntie thinks the world of Peter. Both Auntie E and Auntie C (who are both aunts of Peter), both think that if Peter does something, it's very likely to be the right thing to do. Indeed, they are fairly deferential to Peter in this respect; if Peter does something they thought was wrong, they take that as some (strong but inconclusive) reason to change their belief about the morality of the action.

Peter is currently contemplating some action a. Let A be the proposition that Peter does a, and Å be the proposition that doing a is good. For simplicity, assume it is common knowledge that not doing a is good iff doing a is not good, so ~Å can be read as either of the epistemically equivalent propositions _a is not good_ and _not a is good_. 

Before Peter acts, both Auntie's have the same credal distribution, satisfying these constraints.

- C(Å | A) = 0.8
- C(~Å | ~A) = 0.9
- C(A) = 0.7

@tbl-credence shows the credence each Auntie has in each of the four possibilities from crossing A with Å.

|    |   Å    |    ¬Å    |
|---:|:------:|:--------:|
| A  |   0.56 |   0.14   |
| ¬A |   0.03 |   0.27   |

Auntie's credence that Peter will do a, and that it will be right. {#tbl-credence}

Now you might think at this point that I've said enough to tell you what each Auntie hopes Peter will do. After all, I've told you everything relevant about each Auntie's credence in Å, and I've told you that their credences in propositions about goodness determine their values. But I haven't told you one thing extra - I haven't told you what decision theory the two Aunties follow.

Auntie C endorses a version of causal decision theory, in particular something like the version supported by David @Lewis1981a. Here I'm following Collins, who notes that it is odd that Lewis attributes to Auntie a form of evidential decision theory, which Lewis himself does not endorse. We'll return to this point in a bit. In particular, Auntie's values are given by the following formula. In the formula, let x be an arbitrary action, from some set Y of options, and X be the proposition that it is performed. Let G be the proposition that a good option from Y is chosen. (We're still assuming that actions are only good or bad, though it isn't too hard to allow other values in.) Let C~x~ be the result of _imaging_ the credence function C on the proposition x is performed, where we assume that changing the descriptive facts is a smaller change for imaging purposes than changing the moral facts. For example, consider the world where Peter does a, and that is good, and ask, what is the image of that world under the assumption that Peter does not do a. It is the world where Peter does not do a, and that is bad. That is, we hold fixed that a is good, not that Peter does something good.

With all that in place, Auntie C's view is easy to state.

> V(x) = C_X_(G)

This resembles equation (11) in "Causal Decision Theory". Indeed, after the first character, it just is the special case of that equation where the only possible values are 1 and 0. But the first character matters. Lewis is presenting a theory of usefulness, not of value. His formula is meant to measure the thing that a rational actor maximises. It is not measuring the thing an altruistic friend hopes is maximised. We'll come back to this point in @sec-open-question. For now, I just want to note the similarities to Lewis's own theory.

Using this formula, Auntie C hopes that Peter does a iff C(Å) > C(¬Å). Since C(Å) = 0.59, and C(¬Å) = 0.41, that means she does hope that Peter does A.

Auntie E's view is easier to state. She is an evidential decision theorist. For her, the value of an arbitrary action x is given by this formula.

> V(x) = C(G | X)

That is, she looks at Peter's options, and hopes that he does the one that she is most confident is good, conditional on Peter doing it. That means she hopes Peter does not do a, since then she'll have credence 0.9 that Peter has done the right thing. If Peter does a, she'll only have credence 0.8 that he'll have done the right thing, which isn't as good.

That puts our players on the stage. It's now time to introduce Lewis's argument.

# The Ludovician Argument

I'll present here a somewhat simplified version of Lewis's argument, following the presentation in @Collins2015 and @IttayRozen2014. This version is somewhat simpler than Lewis's, but it's easy to find parts in Lewis's text where he endorses every premise here, and the premises are sufficient to get the result. So I think it's fair to attribute the argument to him.

Assume that we have a finite set of worlds. We will use *w* as a variable over worlds. A world, in this sense, is a specification of the truth value of all the truth-apt things that are relevant to a particular decision. The worlds in this sense are more coarse grained than Ludovician concreta in that they only specify truth values of relevant propositions, not of all propositions. That's why we can assume that there are finitely many of them. But these worlds are more fine grained than Ludovician concreta in a different sense. They will be used to represent moral uncertainty. So there can be pairs of them that are descriptively alike but evaluatively distinct. Given the supervenience of the evaluative on the descriptive, this is impossible for Ludovician worlds.^[That we're using metaphysically impossible worlds should not cause any concern here. As @Chalmers20xx argues, we want the quantifiers here to range over epistemically possible worlds. For people who are unsure of the moral facts, as happens here, that means that there are some metaphysically impossible worlds that are epistemically possible.]

For any descriptive proposition A, assume there is a distinct proposition Å, meaning that A is good. Let V be an agent's value function, and C their credence function, with superscripts representing what those functions are like after updating. So V^A^ and C^A^ are the values of the value and credence functions after updating on A. Strictly speaking given how I've set this up, it is sets of worlds not individual worlds that get values. But I'll sometimes write V(*w*) when strictly it should be V({*w*}); I don't think this can lead to any confusion. (Later I'll also write C(*w*) for the probability of C({*w*}); again it shouldn't result in confusion.)

Lewis's argument against Auntie uses five assumptions. In these assumptions B is an arbitrary proposition, and A is an arbitrary *descriptive* proposition. 

Equation
:    The way to represent Auntie's anti-Humean view is V(A) = C(Å).

Invariance
:    V^A^(*w*) = V(*w*)

Additivity
:    V(A) = Σ~*w*~V(*w*)C(*w* | A)

Restricted Conditionalisation
:    C^A^(B) = C(B | A)

Good-Bad
:    All worlds are either GOOD or BAD. If *w* is GOOD, then V(*w*) = 1, and otherwise V(*w*) = 0.

The last assumption is obviously absurd, but it is useful for setting out the argument. In any case, if the first four assumptions are true, then they should be consistent with **Good-Bad**. Given those assumptions, here is Lewis's argument.

|   |           |              |
|--:|:----------|:-------------|
| C(Å) | = V(A) |               |
|       | = Σ~*w*~V(*w*) C(*w* \| A) | (**Additivity**) |
|       | = Σ~*w*~V^A^(*w*) C(*w* \| A) | (**Invariance**) |
|       | = Σ~*w*~V^A^(*w*) C^A^(*w* \| A) | (**Restricted Conditionalisation**) |
|       | = V^A^(A) | (**Additivity**, applied to updated values) |
|       | = C^A^(Å) | (**Equation**, again after updating) |
|       | = C(Å \| A) | (**Restriced Conditionalisation**) |

But it is absurd that A and Å are independent. At least, it's absurd if evaluative uncertainty is coherent. It's possible to be like Auntie and not know whether A is true, but think that it being true is evidence that it is good.

At this point Lewis does not rely on the intuition that Auntie's case is possible, but instead gives an argument that A and Å cannot always be independent. It goes roughly like this.

1. It is possible that someone could have positive credence in all four cells of @tbl-credence.
2. It is further possible that such a person could learn A ∨ Å and nothing else.
3. If such a person learned A ∨ Å and nothing else, they should update by conditionalisation on A ∨ Å.
4. From 1-3, plus some algebra, it follows that A and Å will not be independent post-conditionalisation.
5. But the earlier argument shows that Desire-as-Belief implies A and Å will be independent after any possible learning experience.

The problem is that step 3 is not particularly plausible. If moral beliefs have centered world contents, the kind of content described in @Lewis1979x, then they probably should not be updated by conditionalisation. On most views of learning what time it is, the learner does not update by conditionalisation. And moral beliefs plausibly do have centered world contents; that is a natural interpretation of the meta-ethical view that Lewis himself endorses [@Lewis1989x].

I don't mean to endorse the objection to premise 3 in the last paragraph; I think the questions here are rather tricky. I do mean to endorse two other claims. One is that just thinking about cases like Peter and his Aunties gives us a stronger reason to reject independence than Lewis's argument from conditionalisation. Second, if one does think that independence is independently implausible, Lewis only needs **Restricted Conditionalisation** for the rest of the argument to work. And **Restricted Conditionalisation** is plausible, even if one rejects conditionalisation for centered worlds contents.

# Aunties' Responses

With the argument in front of us, it's easy enough to see how the Aunties can respond. Auntie E rejects **Equation**, and Auntie C rejects **Additivity**. The main point of this section is to argue that each Auntie has a principled reason to reject the premise in Lewis relies on. A secondary point is to argue that this means any desire-as-belief theorist has a reason to reject Lewis's argument.

Let's start with Auntie E. She objects to Lewis's argument in the same way Huw @Price1989 does - by rejecting **Equation**. According to **Equation**, Auntie should value propositions according to her current evaluations of the goodness of the proposition. But Auntie E thinks that gets Peter's case wrong, and for a simple reason. How valuable a proposition is not a function of how likely it is to be good, but how likely it is that it would be good, were it true. That is, Auntie's view is not **Equation**, but V(A) = Pr(Å | A). This is exactly what Price recommended Auntie adopt immediately after Lewis's first paper on desire-as-belief came out.

In the sequel paper Lewis has a response to Price's suggestion. As @Hajek2015 observes, it is very hard to understand what the response really is. Lewis states the kind of view Price endorses, makes a couple of observations about it, and then ends as if the question is settled. If it's meant to be a reductio, it's really not clear what the implausible conclusion is. Hàjek speculates that a paragraph or more simply went missing; the text is puzzling enough to take such speculations seriously.^[Since Hàjek's paper was published, we've had two volumes of correspondence by Lewis published [@LewisLetters1; @LewisLetters2]. But unfortunately nothing in them sheds light on this interpretative question.]

Now let's consider Auntie C. She thinks that **Additivity** is wrong because it gets Peter's case wrong. She thinks it gets the case wrong for a simple reason: it's the way evidential decision theorists value gambles, and she's a causal decision theorist, not an evidential decision theorist.^[So far Auntie C is following closely the argument in @Collins2015, though she will ultimately disagree with Collins on a point of detail: Auntie accepts **Restricted Conditionalisation**.]

Again, Lewis has a response. He says that this is to confuse choice-worthiness and desirability.

> A famous difficulty need not concern us here. Suppose a certain action would serve as an effective means to your ends. Yet at the same time it would constitute evidence—evidence available to you in no other way—that you are predestined inescapably to some dreadful misfortune. Should you perform that action?—Yes; your destiny is not a consideration, since that is outside your control. Do you desire to perform it?—No; you want good news, not bad. Since our topic here is not choiceworthiness but desire, and since the two diverge, we adopt an “evidential” conception of expected value, on which the value of the useful action that brings bad news is low. Choiceworthiness is governed by a different, “causal”, conception of expected value. [@Lewis1996 304]

Auntie finds this very puzzling. Imagine a person, call them Rosencrantz, is playing Newcomb's Problem. It sounds like Lewis is saying that Rosencrantz should (a) take both boxes, and (b) desire that they take one box. But that means that their actions won't flow from their desires in the way that Humeans, like Lewis, say that they should. Indeed, one of the motivations of the first Desire as Belief paper, right on the first page, was preserving the link between desire and action.

So Auntie C is unmoved. She wants what is best, and she doesn't want people to do things just so she'll have evidence that things are better than she thought.

Let's sum up. Lewis showed that it is impossible to hold onto the four named principles, Auntie's anti-Humean view, and probabilistic dependence between A and Å. The argument that this combination is untenable seems sound. And I think (though some disagree) that we should hold on to **Invariance**, **Restricted Conditionalisation** and the possibility of probabilistic dependence. The question then is which of these three to give up:

1. Anti-Humeanism
2. **Equation**
3. **Additivity**

My argument is that Lewis has not given us a compelling reason to reject 1, rather than rejecting 2 or 3. What's tricky about the case is that it's hard to say which of 2 or 3 we should reject. One kind of anti-Humean, Auntie E, rejects 2, since she thinks that desirability tracks the conditional probability of an act being good. Another kind of anti-Humean, Auntie C, rejects 3, since she thinks desirability goes with causal choice-worthiness. Both these rejections seem principled, so either anti-Humean has a principled reason to reject Lewis's argument.

# A Decision Problem {#sec-decision}

To back this point up, imagine Peter is not making a morally loaded decision. Instead he's playing a version of the problem @Skyrms1981 calls Nice Demon. The rules are simple.

1. Peter will choose Up or Down.
2. Demon will try to predict Peter's choice.
3. If Demon's prediction is correct, Peter gets $1. Otherwise he gets nothing.
4. Demon is 0.9 likely to correctly predict Down (if Peter chooses it), and 0.8 likely to correctly predict Up (if Peter chooses it).

Both Aunties start deliberation with credence 0.7 that Peter will choose Up. Question: What does Auntie hope that Peter will do? Answer: They disagree.

Auntie C hopes that Peter will choose Up. She has credence 0.59 that Demon has predicted Up, and she wants Peter to get the money. This case is, for her, another counterexample to **Additivity**.

Auntie E hopes that Peter will choose Down. She agrees with Lewis on what is desirable, i.e., she thinks desire goes with evidential choice-worthiness. This case is, for her, another reason to reject **Equation**.

Who should accept both **Addivity** and **Equation**? Only someone who thinks Peter should choose both Up and Down. That's implausible, so 

