---
title: "Low Stakes Pragmatic Encroachment"
author: "Anon"
date: "`r Sys.Date()`"
output:
  bookdown::word_document2:
    number_sections: yes
  bookdown::pdf_document2:
    latex_engine: xelatex
    toc: no
    keep_tex: yes
mainfont: Lato
mathfont: Fira Math
mainfontoptions: Scale=MatchLowercase
geometry: margin=1.5in
linestretch: 1.1
bibliography: ../rBib.bib
fontsize: 12pt
indent: yes
---

Both friends and foes of interest-relative theories of knowledge typically take it for granted that interest-relativity matters primarily in so-called high stakes situations. This paper presents a short argument that this is not so. The logic of interest-relativity applies just as much to low stakes situations as high stakes ones. Indeed, there is a recipe for generating cases where interests matter in cases where the stakes are arbitrarily low, and the proposition in question is arbitrarily well supported by the evidence. Now some may take this to be a reductio of interest-relative (or pragmatic encroachment) theories. I'll argue that this is not the right response; anti-encroachment theories are not well placed to explain what's going on in these theories.

# The Main Example

Our main example is a game, which I'll call the Red-Blue game.

1.  Two sentences will be written on the board, one in red, one in blue.
2.  The player will make two choices.
3.  First, they will pick a colour, red or blue.
4.  Second, they say whether the sentence in that colour is true or
	false.
5.  If they are right, they win. If not, they lose.
6.  If they win, they get $50, and if they lose, they get nothing.

Our player is called Chooser. Chooser prefers having more money to less, so she wants to win the game. She has been reading some medieval history, and last night was reading about the Battle of Agincourt. She was amused to see that it too place on her birthday, October 25, and in 1415, precisely 600 years before her own birthday. The book says all these things about the Battle of Agincourt because they are actually true, and when she read the book, Chooser believed them. She believed them because she had lots of independent evidence that the book was reliable (it came from a respected author and publisher, it didn't contradict her well-grounded background beliefs), and she was sensitive to that evidence of its reliability. And, indeed, the book was generally reliable, as well as accurate on this point.

Chooser comes to know that she is playing the Red-Blue game, and that these are its rules. She does not come to know any other relevant fact about the game. When the game starts, the following two sentences are written on the board, the first in red, the second in blue.

-  Two plus two equals four.
-  The Battle of Agincourt took place in 1415.

Chooser looks at this, thinks to herself, "Oh, my book said that the Battle of Agincourt was in 1415, so (given the rules of the game) playing Blue-True will be as good as any other play, so I'm playing Blue-True. Playing Red-True would get the same amount, since obviously two plus two is four, but I'm going to play Blue-True instead". And that's what she does, and she wins the $50.

Intuitively, Chooser's move here is irrational. It doesn't cost her anything—she gets the $50. And it's not that irrational as these things go—she costs herself $50 in the somewhat distant worlds where her reliable book gets this fact wrong. But it was still irrational. She took a needless risk, when there was a simple safe option on the table.

Chooser's case isn't a zero stakes case; $50 is $50. But it is low stakes. The intuition that Chooser is being irrational persists if the stakes fall somewhat. Maybe at a low enough number, it becomes a matter of indifference what Chooser does. But as it stands, this is irrational.

And this is enough to generate an argument for interest-relativity, given an assumption that interest-relative theorists typically make. The assumption is what Jessica Brown calls SUFF.

> SUFF: If you know that $p$ then it is appropriatye to rely on $p$ in practical reasoning. [@Brown2008, 168]

Assume, for reductio, that Chooser knows when the Battle of Agincourt was at the time they are playing the Red-Green game. Then they can reason as follows.

1. If the Battle of Agincourt was in 1415, then playing Blue-True will win $50.
2. The Battle of Agincourt was in 1415.
3. So, playing Blue-True will win $50. (from 1, 2)
4. Playing anything else will win at most $50.
5. If one option will do at least as well as any other option may do, then I may play that option.
6. So I may play Blue-True. (from 3, 4, 5)

And that last step is false. Since the only premise that is contentious here is premise 2, it follows that they cannot use 2 as a premise in this practical reasoning. And by SUFF, that means that they don't know premise 2.

Here is another way to the same conclusion. Imagine that Chooser's twin is playing this variant of the Red-Bluegame. There is just one sentence written on the board, in red. The twin can still play the same four options as Chooser. If they play Red-True(/False) they will win iff the red sentence is true(/false). If they play Blue-True they win, and if they play Blue-False they lose. Winning gets $50, not winning gets nothing. All of this (and nothing else relevant) is known by the twin. Intuitively, it is (at least) permissible for the twin to play Blue-True, since they can motivate it by a weak dominance argument. If Chooser can rely on the Battle of Agincourt having been in 1415, then her practical situation is exactly like her twin's. So she can permissibly do what her twin does. So she can play Blue-True. But she cannot do that. So her practical situation is different to her twin's. So she cannot rely on the date of the Battle of Agincourt. So, by SUFF, she doesn't know it.

In the recent literature, arguments for and against interest-relativity have primarily focused on high stakes examples, rather than low stakes examples like Chooser's. But the example is not entirely novel. Its structure is similar, in the features that matter to me, to the examples of low-cost checking that Bradley Armour-Garb ~[-@ArmourGarb2011]~ discusses. (Though he draws contextualist conclusions from these examples, not interest-relative ones.) And it is similar to some of the cases of three-way choice that Charity Anderson and John Hawthorne deploy in arguing against interest-relativity ~[-@AndersonHawthorne2019a; -@AndersonHawthorne2019b]~. Though they too draw anti-encroachment conclusions from these cases. Indeed, one of the conclusions they draw is that the notion of high stakes is too unclear to use in philosophical theorising (which I agree with), and this is bad news for interest-relative theories (which I think doesn't follow). 
But mostly people have focussed on cases like the this one.

Here is an example that is more familiar from the recent literature. Last night, Blaise was reading the same book that Chooser was reading. And he too was struck by the fact that the Battle of Agincourt took place on October 25, 1415. Today he is visited by a representative of the supernatural world, and offered the following bet. (Blaise knows these are the terms of the bet, and doesn't know anything else relevant.) If he declines the bet, life will go on as normal. If he accepts, one of two things will happen.

- If it is true that the Battle of Agincourt took place in 1415, an infant somewhere will receive one second's worth of pure joy, of the kind infants often get playing peek-a-boo.
- If it is false that the Battle of Agincourt took place in 1415, all of humanity will be cast into The Bad Place for all of eternity.

Blaise takes the bet. The Battle of Agincourt was in 1415, and he can't bear the thought of a lovable baby missing that second of pure joy.
 
Again, there is an intuition that Blaise did something horribly wrong here. And this intuition is best explained, I will argue, by letting knowledge be interest-relative. But the argument that the interest-relativity of knowledge is the very best explanation of what's going on is, in my view, somewhat weaker in Blaise's case than in Chooser's. It's not that I think the interest-relative explanation of the case is wrong; in fact I think it's basically correct. It's rather that in Blaise's case there are alternative interest-invariant explanations are somewhat more plausible. So I'll focus on Chooser, not Blaise.

This choice of focus occasionally means that this book is less connected to the existing literature than I would like. I occasionally infer what a philosopher would say about cases like Chooser from what they have said about cases like Blaise. And I suspect in some cases I'll get those inferences wrong. But I want to set out the best argument for the interest-relativity of knowledge that I know, and that means going via the example of Chooser.

Though I am starting with an example, and with an intuition about it, I am not starting with an intuition about what is known in the example. I don't have any clear intuitions about what Chooser knows or doesn't know while playing the Red-Blue game. The intuition that matters here is that her choice of Blue-True is irrational. It's going to be a matter of inference, not intuition, that Chooser lacks knowledge.

And that inference will largely be by process of elimination. In section ~\@ref(fourfamilies)~ I will set out four possible things we can say about Chooser, and argue that one of them must be true. (The argument won't appeal to any principles more controversial than the Law of Excluded Middle.) But all four of them, including the interest-relative view I favour, have fairly counterintuitive consequences. So something counterintuitive is true around here. And this puts a limit on how we can argue. At least one instance of the argument _this is counterintuitive, so it is false_ must fail. And that casts doubt over all such arguments. This is a point that critics of interest-relativity haven't sufficiently acknowledged, but it also puts constraints on how one can defend interest-relativity.

When Chooser starts playing the Red-Blue game, her practical situation changes. So you might think I've gone wrong in stressing Chooser's interests, not her practical situation. I've put the focus on interests for two reasons. One is that if Chooser is totally indifferent to money, then there is no rational requirement to play Red-True. We need to posit something about Chooser's interests to even get the data point that the interest-relative theory explains. The second reason, which I'll talk about more in section ~\@ref(whatinterests)~, is that sometimes we can lose knowledge due to a change not in our practical situation, but our theoretical interests.

In the existing literature, views like mine are sometimes called versions of **subject-sensitive invariantism**, since they make knowledge relevant to the stakes and salient alternatives available to the subject. But this is a bad name; of course whether a knowledge ascription is true is sensitive to who the subject of the ascription is. I know what I had for breakfast and you (probably) don't. What is distinctive is which features of the subject's situation that the interest-relative theory says are relevant, and calling it the interest-relative theory of knowledge  makes it clear that it is the subject's interests. In the past, I've called it **interest-relative invariantism**. But, for reasons I'll say more about in section ~\@ref(neutrality)~, I'm not committed to _invariantism_ in this book. So it's just the interest-relative theory, or IRT.
